/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Advertising Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.service.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * CreativeApprovalRestController as REST API
 *
 * <p>Exposes REST endpoints for the CreativeApproval entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Advertising Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model for advertising planning, buying, trafficking, delivery, and measurement.</td></tr>
 *          <tr><td>industry</td><td>Advertising</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	CreativeApprovalBusinessService
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateCreativeApprovalCommand</li>
 *      <li></li>UpdateCreativeApprovalCommand</li>
 *      <liDeleteCreativeApprovalCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/CreativeApproval")
public class CreativeApprovalRestController extends BaseSpringRestController {

    /**
     * Handles create a CreativeApproval.  if not key provided, calls create, otherwise calls save
     * @param		CreativeApproval	creativeApproval
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateCreativeApprovalCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = CreativeApprovalService.getCreativeApprovalInstance().createCreativeApproval( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a CreativeApproval.  if no key provided, calls create, otherwise calls save
     * @param		CreativeApproval creativeApproval
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateCreativeApprovalCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateCreativeApprovalCommand
			// -----------------------------------------------
			completableFuture = CreativeApprovalService.getCreativeApprovalInstance().updateCreativeApproval(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "CreativeApprovalController:update() - successfully update CreativeApproval - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a CreativeApproval entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteCreativeApprovalCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	CreativeApprovalService delegate = CreativeApprovalService.getCreativeApprovalInstance();

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted CreativeApproval with key " + command.getCreativeApprovalId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a CreativeApproval using a UUID
     * @param		UUID uuid 
     * @return		CreativeApproval
     */    
    @GetMapping("/load")
    public CreativeApproval load( @RequestParam(required=true) UUID uuid ) {    	
    	CreativeApproval entity = null;

    	try {  
    		entity = CreativeApprovalService.getCreativeApprovalInstance().getCreativeApproval( new CreativeApprovalFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load CreativeApproval using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all CreativeApproval business objects
     * @return		Set<CreativeApproval>
     */
    @GetMapping("/")
    public List<CreativeApproval> loadAll() {                
    	List<CreativeApproval> creativeApprovalList = null;
        
    	try {
            // load the CreativeApproval
            creativeApprovalList = CreativeApprovalService.getCreativeApprovalInstance().getAllCreativeApproval();
            
            if ( creativeApprovalList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all CreativeApprovals" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all CreativeApprovals ", exc );
        	return null;
        }

        return creativeApprovalList;
                            
    }

    /**
     * save CreativeAsset on CreativeApproval
     * @param		command AssignCreativeAssetToCreativeApprovalCommand
     */     
	@PutMapping("/assignCreativeAsset")
	public void assignCreativeAsset( @RequestBody AssignCreativeAssetToCreativeApprovalCommand command ) {
		try {
			CreativeApprovalService.getCreativeApprovalInstance().assignCreativeAsset( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign CreativeAsset", exc );
        }
	}

    /**
     * unassign CreativeAsset on CreativeApproval
     * @param		 command UnAssignCreativeAssetFromCreativeApprovalCommand
     */     
	@PutMapping("/unAssignCreativeAsset")
	public void unAssignCreativeAsset( @RequestBody(required=true)  UnAssignCreativeAssetFromCreativeApprovalCommand command ) {
		try {
			CreativeApprovalService.getCreativeApprovalInstance().unAssignCreativeAsset( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign CreativeAsset", exc );
		}
	}
	
    /**
     * save Publisher on CreativeApproval
     * @param		command AssignPublisherToCreativeApprovalCommand
     */     
	@PutMapping("/assignPublisher")
	public void assignPublisher( @RequestBody AssignPublisherToCreativeApprovalCommand command ) {
		try {
			CreativeApprovalService.getCreativeApprovalInstance().assignPublisher( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Publisher", exc );
        }
	}

    /**
     * unassign Publisher on CreativeApproval
     * @param		 command UnAssignPublisherFromCreativeApprovalCommand
     */     
	@PutMapping("/unAssignPublisher")
	public void unAssignPublisher( @RequestBody(required=true)  UnAssignPublisherFromCreativeApprovalCommand command ) {
		try {
			CreativeApprovalService.getCreativeApprovalInstance().unAssignPublisher( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Publisher", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected CreativeApproval creativeApproval = null;
    private static final Logger LOGGER = Logger.getLogger(CreativeApprovalRestController.class.getName());
    
}
